name: release_manager  # اسم المشروع
description: A CLI tool for analyzing code changes
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'  # تأكد إن SDK متوافق مع إصدار Dart اللي عندك

dependencies:
  http: ^1.3.0  # مكتبة HTTP لعمل الطلبات

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
